Repository hrach/navigation-compose-ext, pull requests merged in 2024-06, with the labels that each got.

#11 Marked BottomSheet navgraph extension method as public
  bottomsheet/src/main/kotlin/dev/hrach/navigation/bottomsheet/NavGraphBuilder.kt
Labels: semver:patch

#12 Fixed 'unsigneg' typo in workflow
  .github/workflows/release.yml
Labels: skip-changelog, semver:patch

#21 Remove AppCompat dependency from :bottomsheet
  bottomsheet/build.gradle.kts
Labels: bug
